name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Show Python info
        run: |
          python -V
          pip -V

      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install "pytest==8.4.2" "ruff==0.12.11" "black==25.1.0" "mypy==1.17.1"

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Type-check (mypy)
        run: mypy .

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q